apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavenbuildproject-deployment
  labels:
    app: mavenbuild
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mavenbuild
  template:
    metadata:
      labels:
        app: mavenbuild
    spec:
      containers:
      - name: mavenbuild
        image: sachinbabar17/mavenproject1
        ports:
        - containerPort: 8080

kubectl expose --type=NodePort deployment mavenbuildproject-deployment --port 80 --name my-service --overrides '{ "apiVersion": "v1","spec":{"ports": [{"port":80,"protocol":"TCP","targetPort":8080,"nodePort":30080}]}}'
