apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-deployment2
  labels:
    app: maven
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maven
  template:
    metadata:
      labels:
        app: maven
    spec:
      containers:
      - name: mavenserver
        image: sachinbabar17/mavenprojectt:latest
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: maven-service
spec:
  selector:
    app: maven
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 3000
    nodePort: 32760
