apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavenbuild-deployment
  labels:
    app: mavenbuild
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mavenbuild
  template:
    metadata:
      labels:
        app: mavenbuild
    spec:
      containers:
      - name: mavenbuild
        image: sachinbabar17/mavenproject1
        ports:
        - containerPort: 8080
